services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - sistecredito

  redisinsight:
    image: redis/redisinsight
    depends_on:
      - redis
    ports:
      - "5540:5540"
    networks:
      - sistecredito

  sql-server:
    image: mcr.microsoft.com/mssql/server
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"
    networks:
      - sistecredito

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=RabbitMQ2023!
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sistecredito

networks:
  sistecredito:
